name: decade
version: 1.0.0
profile: decade
config-version: 2

models:
  decade:
    staging:
      +materialized: view
    marts:
      +materialized: table
    consumption:
      +materialized: view
