-- One row per lot (snapshot_id, investment_id): the lot's detail and balances
-- payloads joined and flattened into typed columns.
SELECT
    snapshot_id,
    investment_id,
    TRY_CAST(coalesce(det.snapshot_created_at, bal.snapshot_created_at) AS TIMESTAMP) AS snapshot_created_at,
    coalesce(det.institution_id,   bal.institution_id)   AS institution_id,
    coalesce(det.institution_name, bal.institution_name) AS institution_name,
    coalesce(det.party_id,         bal.party_id)         AS party_id,
    coalesce(det.account_id,       bal.account_id)       AS account_id,
    coalesce(det.connection_id,    bal.connection_id)    AS connection_id,
    {{ payload_field('det', 'issuerInstitutionCnpjNumber',             'VARCHAR') }}       AS issuer_cnpj,
    {{ payload_field('det', 'isinCode',                                'VARCHAR') }}       AS isin_code,
    {{ payload_field('det', 'investmentType',                          'VARCHAR') }}       AS product_type,
    {{ payload_field('det', 'debtorCnpjNumber',                        'VARCHAR') }}       AS debtor_cnpj,
    {{ payload_field('det', 'debtorName',                              'VARCHAR') }}       AS debtor_name,
    {{ payload_field('det', 'taxExemptProduct',                        'VARCHAR') }}       AS tax_exempt,
    {{ payload_field('det', 'remuneration.indexer',                    'VARCHAR') }}       AS indexer,
    {{ payload_field('det', 'remuneration.preFixedRate',               'DECIMAL(12,6)') }} AS pre_fixed_rate,
    {{ payload_field('det', 'remuneration.postFixedIndexerPercentage', 'DECIMAL(12,6)') }} AS post_fixed_indexer_pct,
    {{ payload_field('det', 'issueUnitPrice.amount',                   'DECIMAL(18,4)') }} AS issue_unit_price,
    {{ payload_field('det', 'issueDate',                               'DATE') }}          AS issue_date,
    {{ payload_field('det', 'dueDate',                                 'DATE') }}          AS due_date,
    {{ payload_field('det', 'clearingCode',                            'VARCHAR') }}       AS clearing_code,
    {{ payload_field('det', 'purchaseDate',                            'DATE') }}          AS purchase_date,
    {{ payload_field('bal', 'referenceDateTime',              'TIMESTAMP') }}     AS reference_datetime,
    {{ payload_field('bal', 'updatedUnitPrice.amount',        'DECIMAL(18,4)') }} AS updated_unit_price,
    {{ payload_field('bal', 'quantity',                       'DECIMAL(24,8)') }} AS quantity,
    {{ payload_field('bal', 'grossAmount.amount',             'DECIMAL(18,4)') }} AS gross_amount,
    {{ payload_field('bal', 'netAmount.amount',               'DECIMAL(18,4)') }} AS net_amount,
    {{ payload_field('bal', 'incomeTax.amount',               'DECIMAL(18,4)') }} AS income_tax,
    {{ payload_field('bal', 'financialTransactionTax.amount', 'DECIMAL(18,4)') }} AS transaction_tax,
    {{ payload_field('bal', 'blockedBalance.amount',          'DECIMAL(18,4)') }} AS blocked_amount,
    {{ payload_field('bal', 'purchaseUnitPrice.amount',       'DECIMAL(18,4)') }} AS purchase_unit_price,
    {{ payload_field('bal', 'grossAmount.currency',           'VARCHAR') }}       AS currency
{{ from_positions('CREDIT_FIXED_INCOMES') }}
