-- One row per transaction (snapshot_id, payload_source, investment_id, transaction_id).
SELECT
    snapshot_id,
    payload_source,
    TRY_CAST(snapshot_created_at AS TIMESTAMP) AS snapshot_created_at,
    institution_id,
    institution_name,
    party_id,
    account_id,
    connection_id,
    investment_id,
    {{ txn_field('transactionId',                  'VARCHAR') }}       AS transaction_id,
    {{ txn_field('type',                           'VARCHAR') }}       AS movement_type,
    {{ txn_field('transactionType',                'VARCHAR') }}       AS transaction_type,
    {{ txn_field('transactionTypeAdditionalInfo',  'VARCHAR') }}       AS transaction_type_info,
    {{ txn_field('transactionDate',                'DATE') }}          AS transaction_date,
    {{ txn_field('transactionUnitPrice.amount',    'DECIMAL(18,4)') }} AS transaction_unit_price,
    {{ txn_field('transactionQuantity',            'DECIMAL(24,8)') }} AS transaction_quantity,
    {{ txn_field('transactionGrossValue.amount',   'DECIMAL(18,4)') }} AS transaction_gross_value,
    {{ txn_field('incomeTax.amount',               'DECIMAL(18,4)') }} AS income_tax,
    {{ txn_field('financialTransactionTax.amount', 'DECIMAL(18,4)') }} AS transaction_tax,
    {{ txn_field('transactionNetValue.amount',     'DECIMAL(18,4)') }} AS transaction_net_value,
    {{ txn_field('remunerationTransactionRate',    'DECIMAL(12,6)') }} AS remuneration_rate,
    {{ txn_field('indexerPercentage',              'DECIMAL(12,6)') }} AS indexer_percentage,
    {{ txn_field('transactionGrossValue.currency', 'VARCHAR') }}       AS currency
{{ from_transactions('BANK_FIXED_INCOMES') }}
